import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const src=fs.readFileSync(new URL('../public/index.html',import.meta.url),'utf8');
function fn(name){const start=src.indexOf('function '+name+'(');return src.slice(start,src.indexOf('\n}\n',start)+3)}
const esc=s=>String(s).replaceAll('<','&lt;').replaceAll('"','&quot;');
const header=new Function('esc','dbLeadQuestionClosed','dbLeadStateUnresolved','dbLeadOpenQuestionKind','v3LeadStatus',fn('renderBriefingDashboardHeader')+';return renderBriefingDashboardHeader;')(esc,l=>l.closed,l=>l.unresolved,l=>l.question,l=>l.status);
test('dashboard never invents completion from an empty list or a clock',()=>{const html=header([],'2026-10-07',null);assert.equal((html.match(/Nicht bestätigt/g)||[]).length,4);assert.doesNotMatch(html,/db-tone-green|Alles andere läuft/);assert.match(html,/0 grün/)});
test('questions and unresolved states override a stale green lead status',()=>{const html=header([{status:'green',question:true},{status:'green',unresolved:true},{status:'red'},{status:'red',deleted:true}],'2026-10-07',{slotReceipts:{process09:{receiptId:'r'}}});assert.match(html,/0 grün/);assert.match(html,/1 gelb/);assert.match(html,/1 rot/);assert.match(html,/1 ungeklärt/);assert.equal((html.match(/Laufbeleg vorhanden/g)||[]).length,1);assert.match(html,/db-tone-red/)});
test('calendar hides cached events while disconnected and escapes sources',()=>{const w={gcalStatusSnapshot:()=>({connected:false}),gcalEventsInRange:()=>[{summary:'secret'}]};const render=new Function('window','v3KalenderZeile','dbSafeSourceUrl','esc',fn('renderBriefingAppointments')+';return renderBriefingAppointments;')(w,()=> 'Nicht verbunden',u=>/^https:/.test(u||'')?u:'',esc);assert.doesNotMatch(render('2026-10-07','2026-10-14'),/secret/);w.gcalStatusSnapshot=()=>({connected:true,brRange:{min:'2026-10-07',max:'2026-10-14'}});w.gcalEventsInRange=()=>[{summary:'<img>',htmlLink:'javascript:alert(1)',start:{date:'2026-10-07'}}];const html=render('2026-10-07','2026-10-14');assert.match(html,/&lt;img>/);assert.doesNotMatch(html,/javascript:/)});
test('shared capture retains its queue outside the dashboard',()=>{const render=new Function('window','coreAuthCurrentUser','esc',fn('renderBriefingQuickLead')+';return renderBriefingQuickLead;')({},()=>null,esc);assert.match(render([]),/id="dbQuickCaptureQueue"/);assert.doesNotMatch(render([],{externalQueue:true}),/id="dbQuickCaptureQueue"/)});
